---
apiVersion: v1
kind: Service
metadata:
  name: infisical-service
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

