apiVersion: v1
target: prebuilt
output:
  binaries:
    - 
      id: kubeadm
      name: kubeadm-v1.33.3,pkg/kube/v1.33.3
      amd64: https://dl.k8s.io/release/v1.33.3/bin/linux/amd64/kubeadm
      arm64: https://dl.k8s.io/release/v1.33.3/bin/linux/arm64/kubeadm
    - 
      id: kubelet
      name: kubelet-v1.33.3,pkg/kube/v1.33.3
      amd64: https://dl.k8s.io/release/v1.33.3/bin/linux/amd64/kubelet
      arm64: https://dl.k8s.io/release/v1.33.3/bin/linux/arm64/kubelet
    - 
      id: kubectl
      name: kubectl-v1.33.3,pkg/kube/v1.33.3
      amd64: https://dl.k8s.io/release/v1.33.3/bin/linux/amd64/kubectl
      arm64: https://dl.k8s.io/release/v1.33.3/bin/linux/arm64/kubectl
  containers:
    -
      name: owncloudci/wait-for:latest
    -
      name: liangjw/kube-webhook-certgen:v1.1.1
    - 
      name: alpine:3.14
    -
      name: beclab/kube-rbac-proxy:0.19.0
    - 
      name: registry.k8s.io/kube-apiserver:v1.33.3
    - 
      name: registry.k8s.io/kube-scheduler:v1.33.3
    - 
      name: registry.k8s.io/kube-proxy:v1.33.3
    - 
      name: registry.k8s.io/kube-controller-manager:v1.33.3
    - 
      name: registry.k8s.io/pause:3.10

# must have blank new line