bfl:
  nodeport: 30883
  nodeport_ingress_http: 30083
  nodeport_ingress_https: 30082
  username: 'test'
  url: 'test'
  nodeName: test
pvc:
  userspace: test
userspace:
  userData: test/Home
  appData: test/Data
  appCache: test
  dbdata: test
docs:
  nodeport: 30881
desktop:
  nodeport: 30180
os:
  profile:
    appKey: '${ks[0]}'
    appSecret: test
  studio:
    appKey: '${ks[0]}'
    appSecret: test
  desktop:
    appKey: '${ks[0]}'
    appSecret: test
  message:
    appKey: '${ks[0]}'
    appSecret: test
  rss:
    appKey: '${ks[0]}'
    appSecret: test
  search:
    appKey: '${ks[0]}'
    appSecret: test
  search2:
    appKey: '${ks[0]}'
    appSecret: test
  settings:
    appKey: '${ks[0]}'
    appSecret: test
  dashboard:
    appKey: '${ks[0]}'
    appSecret: test
